export const SET_SEARCHED_RECIPES = 'SET_SEARCHED_RECIPES';

export const RECIPE_COUNT = 'RECIPE_COUNT';

export const GET_RESPONSE = 'GET_RESPONSE';

export const SET_SEARCH_RECIPES = 'SET_SEARCH_RECIPES';
